<?php
/**
 * ProgramPolicyDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * USM Academic Systems Integration Api
 *
 * Integration API for multiple legacy systems and web apps
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rbsgaridan@usm.edu.ph
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProgramPolicyDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProgramPolicyDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProgramPolicyDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'campus_id' => 'int',
        'real_campus_id' => 'int',
        'college_id' => 'int',
        'program_id' => 'int',
        'term_id' => 'int',
        'usmceefp' => 'int',
        'gpa' => 'float',
        'usmceesp' => 'int',
        'major_disc_id' => 'int',
        'program_limit' => 'int',
        'major_limit' => 'int',
        'program_admitted' => 'int',
        'major_admitted' => 'int',
        'usmceetp' => 'int',
        'campus_name' => 'string',
        'college_name' => 'string',
        'program_name' => 'string',
        'term' => 'string',
        'major_disc_desc' => 'string',
        'real_campus' => 'string',
        'major_inactive' => 'bool',
        'major_disc_code' => 'string',
        'priority' => 'string',
        'program_slot_remaining' => 'int',
        'major_slot_remaining' => 'int',
        'need_hepa_btest' => 'bool',
        'status' => 'string',
        'reservation_status' => 'string',
        'pending_count' => 'int',
        'reserved_count' => 'int',
        'approved_count' => 'int',
        'denied_count' => 'int',
        'total_count' => 'int',
        'pending_limit' => 'int',
        'program_class_id' => 'int',
        'tenant_id' => 'int',
        'specialization_code' => 'string',
        'program_code' => 'string',
        'confirm_clicked_count' => 'int',
        'confirm_count' => 'int',
        'cee_slots_remaining' => 'int',
        'ranking_slots' => 'int',
        'ranking_open_slots' => 'int',
        'ranking_open_slots_remaining' => 'int',
        'open_for_ranking' => 'bool',
        'ranged_cut_off' => 'bool',
        'allowed_specialization' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'campus_id' => 'int32',
        'real_campus_id' => 'int32',
        'college_id' => 'int32',
        'program_id' => 'int32',
        'term_id' => 'int32',
        'usmceefp' => 'int32',
        'gpa' => 'double',
        'usmceesp' => 'int32',
        'major_disc_id' => 'int32',
        'program_limit' => 'int32',
        'major_limit' => 'int32',
        'program_admitted' => 'int32',
        'major_admitted' => 'int32',
        'usmceetp' => 'int32',
        'campus_name' => null,
        'college_name' => null,
        'program_name' => null,
        'term' => null,
        'major_disc_desc' => null,
        'real_campus' => null,
        'major_inactive' => null,
        'major_disc_code' => null,
        'priority' => null,
        'program_slot_remaining' => 'int32',
        'major_slot_remaining' => 'int32',
        'need_hepa_btest' => null,
        'status' => null,
        'reservation_status' => null,
        'pending_count' => 'int32',
        'reserved_count' => 'int32',
        'approved_count' => 'int32',
        'denied_count' => 'int32',
        'total_count' => 'int32',
        'pending_limit' => 'int32',
        'program_class_id' => 'int32',
        'tenant_id' => 'int32',
        'specialization_code' => null,
        'program_code' => null,
        'confirm_clicked_count' => 'int32',
        'confirm_count' => 'int32',
        'cee_slots_remaining' => 'int32',
        'ranking_slots' => 'int32',
        'ranking_open_slots' => 'int32',
        'ranking_open_slots_remaining' => 'int32',
        'open_for_ranking' => null,
        'ranged_cut_off' => null,
        'allowed_specialization' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'campus_id' => true,
        'real_campus_id' => true,
        'college_id' => true,
        'program_id' => true,
        'term_id' => true,
        'usmceefp' => true,
        'gpa' => true,
        'usmceesp' => true,
        'major_disc_id' => true,
        'program_limit' => true,
        'major_limit' => true,
        'program_admitted' => true,
        'major_admitted' => true,
        'usmceetp' => true,
        'campus_name' => true,
        'college_name' => true,
        'program_name' => true,
        'term' => true,
        'major_disc_desc' => true,
        'real_campus' => true,
        'major_inactive' => true,
        'major_disc_code' => true,
        'priority' => true,
        'program_slot_remaining' => true,
        'major_slot_remaining' => true,
        'need_hepa_btest' => true,
        'status' => true,
        'reservation_status' => true,
        'pending_count' => false,
        'reserved_count' => false,
        'approved_count' => false,
        'denied_count' => false,
        'total_count' => false,
        'pending_limit' => false,
        'program_class_id' => false,
        'tenant_id' => true,
        'specialization_code' => true,
        'program_code' => true,
        'confirm_clicked_count' => false,
        'confirm_count' => false,
        'cee_slots_remaining' => false,
        'ranking_slots' => true,
        'ranking_open_slots' => true,
        'ranking_open_slots_remaining' => true,
        'open_for_ranking' => true,
        'ranged_cut_off' => true,
        'allowed_specialization' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'campus_id' => 'campusId',
        'real_campus_id' => 'realCampusId',
        'college_id' => 'collegeId',
        'program_id' => 'programId',
        'term_id' => 'termId',
        'usmceefp' => 'usmceefp',
        'gpa' => 'gpa',
        'usmceesp' => 'usmceesp',
        'major_disc_id' => 'majorDiscId',
        'program_limit' => 'programLimit',
        'major_limit' => 'majorLimit',
        'program_admitted' => 'programAdmitted',
        'major_admitted' => 'majorAdmitted',
        'usmceetp' => 'usmceetp',
        'campus_name' => 'campusName',
        'college_name' => 'collegeName',
        'program_name' => 'programName',
        'term' => 'term',
        'major_disc_desc' => 'majorDiscDesc',
        'real_campus' => 'realCampus',
        'major_inactive' => 'majorInactive',
        'major_disc_code' => 'majorDiscCode',
        'priority' => 'priority',
        'program_slot_remaining' => 'programSlotRemaining',
        'major_slot_remaining' => 'majorSlotRemaining',
        'need_hepa_btest' => 'needHepaBtest',
        'status' => 'status',
        'reservation_status' => 'reservationStatus',
        'pending_count' => 'pendingCount',
        'reserved_count' => 'reservedCount',
        'approved_count' => 'approvedCount',
        'denied_count' => 'deniedCount',
        'total_count' => 'totalCount',
        'pending_limit' => 'pendingLimit',
        'program_class_id' => 'programClassId',
        'tenant_id' => 'tenantId',
        'specialization_code' => 'specializationCode',
        'program_code' => 'programCode',
        'confirm_clicked_count' => 'confirmClickedCount',
        'confirm_count' => 'confirmCount',
        'cee_slots_remaining' => 'ceeSlotsRemaining',
        'ranking_slots' => 'rankingSlots',
        'ranking_open_slots' => 'rankingOpenSlots',
        'ranking_open_slots_remaining' => 'rankingOpenSlotsRemaining',
        'open_for_ranking' => 'openForRanking',
        'ranged_cut_off' => 'rangedCutOff',
        'allowed_specialization' => 'allowedSpecialization'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'campus_id' => 'setCampusId',
        'real_campus_id' => 'setRealCampusId',
        'college_id' => 'setCollegeId',
        'program_id' => 'setProgramId',
        'term_id' => 'setTermId',
        'usmceefp' => 'setUsmceefp',
        'gpa' => 'setGpa',
        'usmceesp' => 'setUsmceesp',
        'major_disc_id' => 'setMajorDiscId',
        'program_limit' => 'setProgramLimit',
        'major_limit' => 'setMajorLimit',
        'program_admitted' => 'setProgramAdmitted',
        'major_admitted' => 'setMajorAdmitted',
        'usmceetp' => 'setUsmceetp',
        'campus_name' => 'setCampusName',
        'college_name' => 'setCollegeName',
        'program_name' => 'setProgramName',
        'term' => 'setTerm',
        'major_disc_desc' => 'setMajorDiscDesc',
        'real_campus' => 'setRealCampus',
        'major_inactive' => 'setMajorInactive',
        'major_disc_code' => 'setMajorDiscCode',
        'priority' => 'setPriority',
        'program_slot_remaining' => 'setProgramSlotRemaining',
        'major_slot_remaining' => 'setMajorSlotRemaining',
        'need_hepa_btest' => 'setNeedHepaBtest',
        'status' => 'setStatus',
        'reservation_status' => 'setReservationStatus',
        'pending_count' => 'setPendingCount',
        'reserved_count' => 'setReservedCount',
        'approved_count' => 'setApprovedCount',
        'denied_count' => 'setDeniedCount',
        'total_count' => 'setTotalCount',
        'pending_limit' => 'setPendingLimit',
        'program_class_id' => 'setProgramClassId',
        'tenant_id' => 'setTenantId',
        'specialization_code' => 'setSpecializationCode',
        'program_code' => 'setProgramCode',
        'confirm_clicked_count' => 'setConfirmClickedCount',
        'confirm_count' => 'setConfirmCount',
        'cee_slots_remaining' => 'setCeeSlotsRemaining',
        'ranking_slots' => 'setRankingSlots',
        'ranking_open_slots' => 'setRankingOpenSlots',
        'ranking_open_slots_remaining' => 'setRankingOpenSlotsRemaining',
        'open_for_ranking' => 'setOpenForRanking',
        'ranged_cut_off' => 'setRangedCutOff',
        'allowed_specialization' => 'setAllowedSpecialization'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'campus_id' => 'getCampusId',
        'real_campus_id' => 'getRealCampusId',
        'college_id' => 'getCollegeId',
        'program_id' => 'getProgramId',
        'term_id' => 'getTermId',
        'usmceefp' => 'getUsmceefp',
        'gpa' => 'getGpa',
        'usmceesp' => 'getUsmceesp',
        'major_disc_id' => 'getMajorDiscId',
        'program_limit' => 'getProgramLimit',
        'major_limit' => 'getMajorLimit',
        'program_admitted' => 'getProgramAdmitted',
        'major_admitted' => 'getMajorAdmitted',
        'usmceetp' => 'getUsmceetp',
        'campus_name' => 'getCampusName',
        'college_name' => 'getCollegeName',
        'program_name' => 'getProgramName',
        'term' => 'getTerm',
        'major_disc_desc' => 'getMajorDiscDesc',
        'real_campus' => 'getRealCampus',
        'major_inactive' => 'getMajorInactive',
        'major_disc_code' => 'getMajorDiscCode',
        'priority' => 'getPriority',
        'program_slot_remaining' => 'getProgramSlotRemaining',
        'major_slot_remaining' => 'getMajorSlotRemaining',
        'need_hepa_btest' => 'getNeedHepaBtest',
        'status' => 'getStatus',
        'reservation_status' => 'getReservationStatus',
        'pending_count' => 'getPendingCount',
        'reserved_count' => 'getReservedCount',
        'approved_count' => 'getApprovedCount',
        'denied_count' => 'getDeniedCount',
        'total_count' => 'getTotalCount',
        'pending_limit' => 'getPendingLimit',
        'program_class_id' => 'getProgramClassId',
        'tenant_id' => 'getTenantId',
        'specialization_code' => 'getSpecializationCode',
        'program_code' => 'getProgramCode',
        'confirm_clicked_count' => 'getConfirmClickedCount',
        'confirm_count' => 'getConfirmCount',
        'cee_slots_remaining' => 'getCeeSlotsRemaining',
        'ranking_slots' => 'getRankingSlots',
        'ranking_open_slots' => 'getRankingOpenSlots',
        'ranking_open_slots_remaining' => 'getRankingOpenSlotsRemaining',
        'open_for_ranking' => 'getOpenForRanking',
        'ranged_cut_off' => 'getRangedCutOff',
        'allowed_specialization' => 'getAllowedSpecialization'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('campus_id', $data ?? [], null);
        $this->setIfExists('real_campus_id', $data ?? [], null);
        $this->setIfExists('college_id', $data ?? [], null);
        $this->setIfExists('program_id', $data ?? [], null);
        $this->setIfExists('term_id', $data ?? [], null);
        $this->setIfExists('usmceefp', $data ?? [], null);
        $this->setIfExists('gpa', $data ?? [], null);
        $this->setIfExists('usmceesp', $data ?? [], null);
        $this->setIfExists('major_disc_id', $data ?? [], null);
        $this->setIfExists('program_limit', $data ?? [], null);
        $this->setIfExists('major_limit', $data ?? [], null);
        $this->setIfExists('program_admitted', $data ?? [], null);
        $this->setIfExists('major_admitted', $data ?? [], null);
        $this->setIfExists('usmceetp', $data ?? [], null);
        $this->setIfExists('campus_name', $data ?? [], null);
        $this->setIfExists('college_name', $data ?? [], null);
        $this->setIfExists('program_name', $data ?? [], null);
        $this->setIfExists('term', $data ?? [], null);
        $this->setIfExists('major_disc_desc', $data ?? [], null);
        $this->setIfExists('real_campus', $data ?? [], null);
        $this->setIfExists('major_inactive', $data ?? [], null);
        $this->setIfExists('major_disc_code', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('program_slot_remaining', $data ?? [], null);
        $this->setIfExists('major_slot_remaining', $data ?? [], null);
        $this->setIfExists('need_hepa_btest', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('reservation_status', $data ?? [], null);
        $this->setIfExists('pending_count', $data ?? [], null);
        $this->setIfExists('reserved_count', $data ?? [], null);
        $this->setIfExists('approved_count', $data ?? [], null);
        $this->setIfExists('denied_count', $data ?? [], null);
        $this->setIfExists('total_count', $data ?? [], null);
        $this->setIfExists('pending_limit', $data ?? [], null);
        $this->setIfExists('program_class_id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('specialization_code', $data ?? [], null);
        $this->setIfExists('program_code', $data ?? [], null);
        $this->setIfExists('confirm_clicked_count', $data ?? [], null);
        $this->setIfExists('confirm_count', $data ?? [], null);
        $this->setIfExists('cee_slots_remaining', $data ?? [], null);
        $this->setIfExists('ranking_slots', $data ?? [], null);
        $this->setIfExists('ranking_open_slots', $data ?? [], null);
        $this->setIfExists('ranking_open_slots_remaining', $data ?? [], null);
        $this->setIfExists('open_for_ranking', $data ?? [], null);
        $this->setIfExists('ranged_cut_off', $data ?? [], null);
        $this->setIfExists('allowed_specialization', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets campus_id
     *
     * @return int|null
     */
    public function getCampusId()
    {
        return $this->container['campus_id'];
    }

    /**
     * Sets campus_id
     *
     * @param int|null $campus_id campus_id
     *
     * @return self
     */
    public function setCampusId($campus_id)
    {
        if (is_null($campus_id)) {
            array_push($this->openAPINullablesSetToNull, 'campus_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campus_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campus_id'] = $campus_id;

        return $this;
    }

    /**
     * Gets real_campus_id
     *
     * @return int|null
     */
    public function getRealCampusId()
    {
        return $this->container['real_campus_id'];
    }

    /**
     * Sets real_campus_id
     *
     * @param int|null $real_campus_id real_campus_id
     *
     * @return self
     */
    public function setRealCampusId($real_campus_id)
    {
        if (is_null($real_campus_id)) {
            array_push($this->openAPINullablesSetToNull, 'real_campus_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('real_campus_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['real_campus_id'] = $real_campus_id;

        return $this;
    }

    /**
     * Gets college_id
     *
     * @return int|null
     */
    public function getCollegeId()
    {
        return $this->container['college_id'];
    }

    /**
     * Sets college_id
     *
     * @param int|null $college_id college_id
     *
     * @return self
     */
    public function setCollegeId($college_id)
    {
        if (is_null($college_id)) {
            array_push($this->openAPINullablesSetToNull, 'college_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('college_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['college_id'] = $college_id;

        return $this;
    }

    /**
     * Gets program_id
     *
     * @return int|null
     */
    public function getProgramId()
    {
        return $this->container['program_id'];
    }

    /**
     * Sets program_id
     *
     * @param int|null $program_id program_id
     *
     * @return self
     */
    public function setProgramId($program_id)
    {
        if (is_null($program_id)) {
            array_push($this->openAPINullablesSetToNull, 'program_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_id'] = $program_id;

        return $this;
    }

    /**
     * Gets term_id
     *
     * @return int|null
     */
    public function getTermId()
    {
        return $this->container['term_id'];
    }

    /**
     * Sets term_id
     *
     * @param int|null $term_id term_id
     *
     * @return self
     */
    public function setTermId($term_id)
    {
        if (is_null($term_id)) {
            array_push($this->openAPINullablesSetToNull, 'term_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('term_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['term_id'] = $term_id;

        return $this;
    }

    /**
     * Gets usmceefp
     *
     * @return int|null
     */
    public function getUsmceefp()
    {
        return $this->container['usmceefp'];
    }

    /**
     * Sets usmceefp
     *
     * @param int|null $usmceefp usmceefp
     *
     * @return self
     */
    public function setUsmceefp($usmceefp)
    {
        if (is_null($usmceefp)) {
            array_push($this->openAPINullablesSetToNull, 'usmceefp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('usmceefp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['usmceefp'] = $usmceefp;

        return $this;
    }

    /**
     * Gets gpa
     *
     * @return float|null
     */
    public function getGpa()
    {
        return $this->container['gpa'];
    }

    /**
     * Sets gpa
     *
     * @param float|null $gpa gpa
     *
     * @return self
     */
    public function setGpa($gpa)
    {
        if (is_null($gpa)) {
            array_push($this->openAPINullablesSetToNull, 'gpa');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gpa', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gpa'] = $gpa;

        return $this;
    }

    /**
     * Gets usmceesp
     *
     * @return int|null
     */
    public function getUsmceesp()
    {
        return $this->container['usmceesp'];
    }

    /**
     * Sets usmceesp
     *
     * @param int|null $usmceesp usmceesp
     *
     * @return self
     */
    public function setUsmceesp($usmceesp)
    {
        if (is_null($usmceesp)) {
            array_push($this->openAPINullablesSetToNull, 'usmceesp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('usmceesp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['usmceesp'] = $usmceesp;

        return $this;
    }

    /**
     * Gets major_disc_id
     *
     * @return int|null
     */
    public function getMajorDiscId()
    {
        return $this->container['major_disc_id'];
    }

    /**
     * Sets major_disc_id
     *
     * @param int|null $major_disc_id major_disc_id
     *
     * @return self
     */
    public function setMajorDiscId($major_disc_id)
    {
        if (is_null($major_disc_id)) {
            array_push($this->openAPINullablesSetToNull, 'major_disc_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_disc_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_disc_id'] = $major_disc_id;

        return $this;
    }

    /**
     * Gets program_limit
     *
     * @return int|null
     */
    public function getProgramLimit()
    {
        return $this->container['program_limit'];
    }

    /**
     * Sets program_limit
     *
     * @param int|null $program_limit program_limit
     *
     * @return self
     */
    public function setProgramLimit($program_limit)
    {
        if (is_null($program_limit)) {
            array_push($this->openAPINullablesSetToNull, 'program_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_limit'] = $program_limit;

        return $this;
    }

    /**
     * Gets major_limit
     *
     * @return int|null
     */
    public function getMajorLimit()
    {
        return $this->container['major_limit'];
    }

    /**
     * Sets major_limit
     *
     * @param int|null $major_limit major_limit
     *
     * @return self
     */
    public function setMajorLimit($major_limit)
    {
        if (is_null($major_limit)) {
            array_push($this->openAPINullablesSetToNull, 'major_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_limit'] = $major_limit;

        return $this;
    }

    /**
     * Gets program_admitted
     *
     * @return int|null
     */
    public function getProgramAdmitted()
    {
        return $this->container['program_admitted'];
    }

    /**
     * Sets program_admitted
     *
     * @param int|null $program_admitted program_admitted
     *
     * @return self
     */
    public function setProgramAdmitted($program_admitted)
    {
        if (is_null($program_admitted)) {
            array_push($this->openAPINullablesSetToNull, 'program_admitted');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_admitted', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_admitted'] = $program_admitted;

        return $this;
    }

    /**
     * Gets major_admitted
     *
     * @return int|null
     */
    public function getMajorAdmitted()
    {
        return $this->container['major_admitted'];
    }

    /**
     * Sets major_admitted
     *
     * @param int|null $major_admitted major_admitted
     *
     * @return self
     */
    public function setMajorAdmitted($major_admitted)
    {
        if (is_null($major_admitted)) {
            array_push($this->openAPINullablesSetToNull, 'major_admitted');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_admitted', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_admitted'] = $major_admitted;

        return $this;
    }

    /**
     * Gets usmceetp
     *
     * @return int|null
     */
    public function getUsmceetp()
    {
        return $this->container['usmceetp'];
    }

    /**
     * Sets usmceetp
     *
     * @param int|null $usmceetp usmceetp
     *
     * @return self
     */
    public function setUsmceetp($usmceetp)
    {
        if (is_null($usmceetp)) {
            array_push($this->openAPINullablesSetToNull, 'usmceetp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('usmceetp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['usmceetp'] = $usmceetp;

        return $this;
    }

    /**
     * Gets campus_name
     *
     * @return string|null
     */
    public function getCampusName()
    {
        return $this->container['campus_name'];
    }

    /**
     * Sets campus_name
     *
     * @param string|null $campus_name campus_name
     *
     * @return self
     */
    public function setCampusName($campus_name)
    {
        if (is_null($campus_name)) {
            array_push($this->openAPINullablesSetToNull, 'campus_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campus_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campus_name'] = $campus_name;

        return $this;
    }

    /**
     * Gets college_name
     *
     * @return string|null
     */
    public function getCollegeName()
    {
        return $this->container['college_name'];
    }

    /**
     * Sets college_name
     *
     * @param string|null $college_name college_name
     *
     * @return self
     */
    public function setCollegeName($college_name)
    {
        if (is_null($college_name)) {
            array_push($this->openAPINullablesSetToNull, 'college_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('college_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['college_name'] = $college_name;

        return $this;
    }

    /**
     * Gets program_name
     *
     * @return string|null
     */
    public function getProgramName()
    {
        return $this->container['program_name'];
    }

    /**
     * Sets program_name
     *
     * @param string|null $program_name program_name
     *
     * @return self
     */
    public function setProgramName($program_name)
    {
        if (is_null($program_name)) {
            array_push($this->openAPINullablesSetToNull, 'program_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_name'] = $program_name;

        return $this;
    }

    /**
     * Gets term
     *
     * @return string|null
     */
    public function getTerm()
    {
        return $this->container['term'];
    }

    /**
     * Sets term
     *
     * @param string|null $term term
     *
     * @return self
     */
    public function setTerm($term)
    {
        if (is_null($term)) {
            array_push($this->openAPINullablesSetToNull, 'term');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('term', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['term'] = $term;

        return $this;
    }

    /**
     * Gets major_disc_desc
     *
     * @return string|null
     */
    public function getMajorDiscDesc()
    {
        return $this->container['major_disc_desc'];
    }

    /**
     * Sets major_disc_desc
     *
     * @param string|null $major_disc_desc major_disc_desc
     *
     * @return self
     */
    public function setMajorDiscDesc($major_disc_desc)
    {
        if (is_null($major_disc_desc)) {
            array_push($this->openAPINullablesSetToNull, 'major_disc_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_disc_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_disc_desc'] = $major_disc_desc;

        return $this;
    }

    /**
     * Gets real_campus
     *
     * @return string|null
     */
    public function getRealCampus()
    {
        return $this->container['real_campus'];
    }

    /**
     * Sets real_campus
     *
     * @param string|null $real_campus real_campus
     *
     * @return self
     */
    public function setRealCampus($real_campus)
    {
        if (is_null($real_campus)) {
            array_push($this->openAPINullablesSetToNull, 'real_campus');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('real_campus', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['real_campus'] = $real_campus;

        return $this;
    }

    /**
     * Gets major_inactive
     *
     * @return bool|null
     */
    public function getMajorInactive()
    {
        return $this->container['major_inactive'];
    }

    /**
     * Sets major_inactive
     *
     * @param bool|null $major_inactive major_inactive
     *
     * @return self
     */
    public function setMajorInactive($major_inactive)
    {
        if (is_null($major_inactive)) {
            array_push($this->openAPINullablesSetToNull, 'major_inactive');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_inactive', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_inactive'] = $major_inactive;

        return $this;
    }

    /**
     * Gets major_disc_code
     *
     * @return string|null
     */
    public function getMajorDiscCode()
    {
        return $this->container['major_disc_code'];
    }

    /**
     * Sets major_disc_code
     *
     * @param string|null $major_disc_code major_disc_code
     *
     * @return self
     */
    public function setMajorDiscCode($major_disc_code)
    {
        if (is_null($major_disc_code)) {
            array_push($this->openAPINullablesSetToNull, 'major_disc_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_disc_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_disc_code'] = $major_disc_code;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return string|null
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param string|null $priority priority
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            array_push($this->openAPINullablesSetToNull, 'priority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('priority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets program_slot_remaining
     *
     * @return int|null
     */
    public function getProgramSlotRemaining()
    {
        return $this->container['program_slot_remaining'];
    }

    /**
     * Sets program_slot_remaining
     *
     * @param int|null $program_slot_remaining program_slot_remaining
     *
     * @return self
     */
    public function setProgramSlotRemaining($program_slot_remaining)
    {
        if (is_null($program_slot_remaining)) {
            array_push($this->openAPINullablesSetToNull, 'program_slot_remaining');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_slot_remaining', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_slot_remaining'] = $program_slot_remaining;

        return $this;
    }

    /**
     * Gets major_slot_remaining
     *
     * @return int|null
     */
    public function getMajorSlotRemaining()
    {
        return $this->container['major_slot_remaining'];
    }

    /**
     * Sets major_slot_remaining
     *
     * @param int|null $major_slot_remaining major_slot_remaining
     *
     * @return self
     */
    public function setMajorSlotRemaining($major_slot_remaining)
    {
        if (is_null($major_slot_remaining)) {
            array_push($this->openAPINullablesSetToNull, 'major_slot_remaining');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('major_slot_remaining', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['major_slot_remaining'] = $major_slot_remaining;

        return $this;
    }

    /**
     * Gets need_hepa_btest
     *
     * @return bool|null
     */
    public function getNeedHepaBtest()
    {
        return $this->container['need_hepa_btest'];
    }

    /**
     * Sets need_hepa_btest
     *
     * @param bool|null $need_hepa_btest need_hepa_btest
     *
     * @return self
     */
    public function setNeedHepaBtest($need_hepa_btest)
    {
        if (is_null($need_hepa_btest)) {
            array_push($this->openAPINullablesSetToNull, 'need_hepa_btest');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('need_hepa_btest', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['need_hepa_btest'] = $need_hepa_btest;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets reservation_status
     *
     * @return string|null
     */
    public function getReservationStatus()
    {
        return $this->container['reservation_status'];
    }

    /**
     * Sets reservation_status
     *
     * @param string|null $reservation_status reservation_status
     *
     * @return self
     */
    public function setReservationStatus($reservation_status)
    {
        if (is_null($reservation_status)) {
            array_push($this->openAPINullablesSetToNull, 'reservation_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reservation_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reservation_status'] = $reservation_status;

        return $this;
    }

    /**
     * Gets pending_count
     *
     * @return int|null
     */
    public function getPendingCount()
    {
        return $this->container['pending_count'];
    }

    /**
     * Sets pending_count
     *
     * @param int|null $pending_count pending_count
     *
     * @return self
     */
    public function setPendingCount($pending_count)
    {
        if (is_null($pending_count)) {
            throw new \InvalidArgumentException('non-nullable pending_count cannot be null');
        }
        $this->container['pending_count'] = $pending_count;

        return $this;
    }

    /**
     * Gets reserved_count
     *
     * @return int|null
     */
    public function getReservedCount()
    {
        return $this->container['reserved_count'];
    }

    /**
     * Sets reserved_count
     *
     * @param int|null $reserved_count reserved_count
     *
     * @return self
     */
    public function setReservedCount($reserved_count)
    {
        if (is_null($reserved_count)) {
            throw new \InvalidArgumentException('non-nullable reserved_count cannot be null');
        }
        $this->container['reserved_count'] = $reserved_count;

        return $this;
    }

    /**
     * Gets approved_count
     *
     * @return int|null
     */
    public function getApprovedCount()
    {
        return $this->container['approved_count'];
    }

    /**
     * Sets approved_count
     *
     * @param int|null $approved_count approved_count
     *
     * @return self
     */
    public function setApprovedCount($approved_count)
    {
        if (is_null($approved_count)) {
            throw new \InvalidArgumentException('non-nullable approved_count cannot be null');
        }
        $this->container['approved_count'] = $approved_count;

        return $this;
    }

    /**
     * Gets denied_count
     *
     * @return int|null
     */
    public function getDeniedCount()
    {
        return $this->container['denied_count'];
    }

    /**
     * Sets denied_count
     *
     * @param int|null $denied_count denied_count
     *
     * @return self
     */
    public function setDeniedCount($denied_count)
    {
        if (is_null($denied_count)) {
            throw new \InvalidArgumentException('non-nullable denied_count cannot be null');
        }
        $this->container['denied_count'] = $denied_count;

        return $this;
    }

    /**
     * Gets total_count
     *
     * @return int|null
     */
    public function getTotalCount()
    {
        return $this->container['total_count'];
    }

    /**
     * Sets total_count
     *
     * @param int|null $total_count total_count
     *
     * @return self
     */
    public function setTotalCount($total_count)
    {
        if (is_null($total_count)) {
            throw new \InvalidArgumentException('non-nullable total_count cannot be null');
        }
        $this->container['total_count'] = $total_count;

        return $this;
    }

    /**
     * Gets pending_limit
     *
     * @return int|null
     */
    public function getPendingLimit()
    {
        return $this->container['pending_limit'];
    }

    /**
     * Sets pending_limit
     *
     * @param int|null $pending_limit pending_limit
     *
     * @return self
     */
    public function setPendingLimit($pending_limit)
    {
        if (is_null($pending_limit)) {
            throw new \InvalidArgumentException('non-nullable pending_limit cannot be null');
        }
        $this->container['pending_limit'] = $pending_limit;

        return $this;
    }

    /**
     * Gets program_class_id
     *
     * @return int|null
     */
    public function getProgramClassId()
    {
        return $this->container['program_class_id'];
    }

    /**
     * Sets program_class_id
     *
     * @param int|null $program_class_id program_class_id
     *
     * @return self
     */
    public function setProgramClassId($program_class_id)
    {
        if (is_null($program_class_id)) {
            throw new \InvalidArgumentException('non-nullable program_class_id cannot be null');
        }
        $this->container['program_class_id'] = $program_class_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            array_push($this->openAPINullablesSetToNull, 'tenant_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets specialization_code
     *
     * @return string|null
     */
    public function getSpecializationCode()
    {
        return $this->container['specialization_code'];
    }

    /**
     * Sets specialization_code
     *
     * @param string|null $specialization_code specialization_code
     *
     * @return self
     */
    public function setSpecializationCode($specialization_code)
    {
        if (is_null($specialization_code)) {
            array_push($this->openAPINullablesSetToNull, 'specialization_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('specialization_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['specialization_code'] = $specialization_code;

        return $this;
    }

    /**
     * Gets program_code
     *
     * @return string|null
     */
    public function getProgramCode()
    {
        return $this->container['program_code'];
    }

    /**
     * Sets program_code
     *
     * @param string|null $program_code program_code
     *
     * @return self
     */
    public function setProgramCode($program_code)
    {
        if (is_null($program_code)) {
            array_push($this->openAPINullablesSetToNull, 'program_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program_code'] = $program_code;

        return $this;
    }

    /**
     * Gets confirm_clicked_count
     *
     * @return int|null
     */
    public function getConfirmClickedCount()
    {
        return $this->container['confirm_clicked_count'];
    }

    /**
     * Sets confirm_clicked_count
     *
     * @param int|null $confirm_clicked_count confirm_clicked_count
     *
     * @return self
     */
    public function setConfirmClickedCount($confirm_clicked_count)
    {
        if (is_null($confirm_clicked_count)) {
            throw new \InvalidArgumentException('non-nullable confirm_clicked_count cannot be null');
        }
        $this->container['confirm_clicked_count'] = $confirm_clicked_count;

        return $this;
    }

    /**
     * Gets confirm_count
     *
     * @return int|null
     */
    public function getConfirmCount()
    {
        return $this->container['confirm_count'];
    }

    /**
     * Sets confirm_count
     *
     * @param int|null $confirm_count confirm_count
     *
     * @return self
     */
    public function setConfirmCount($confirm_count)
    {
        if (is_null($confirm_count)) {
            throw new \InvalidArgumentException('non-nullable confirm_count cannot be null');
        }
        $this->container['confirm_count'] = $confirm_count;

        return $this;
    }

    /**
     * Gets cee_slots_remaining
     *
     * @return int|null
     */
    public function getCeeSlotsRemaining()
    {
        return $this->container['cee_slots_remaining'];
    }

    /**
     * Sets cee_slots_remaining
     *
     * @param int|null $cee_slots_remaining cee_slots_remaining
     *
     * @return self
     */
    public function setCeeSlotsRemaining($cee_slots_remaining)
    {
        if (is_null($cee_slots_remaining)) {
            throw new \InvalidArgumentException('non-nullable cee_slots_remaining cannot be null');
        }
        $this->container['cee_slots_remaining'] = $cee_slots_remaining;

        return $this;
    }

    /**
     * Gets ranking_slots
     *
     * @return int|null
     */
    public function getRankingSlots()
    {
        return $this->container['ranking_slots'];
    }

    /**
     * Sets ranking_slots
     *
     * @param int|null $ranking_slots ranking_slots
     *
     * @return self
     */
    public function setRankingSlots($ranking_slots)
    {
        if (is_null($ranking_slots)) {
            array_push($this->openAPINullablesSetToNull, 'ranking_slots');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ranking_slots', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ranking_slots'] = $ranking_slots;

        return $this;
    }

    /**
     * Gets ranking_open_slots
     *
     * @return int|null
     */
    public function getRankingOpenSlots()
    {
        return $this->container['ranking_open_slots'];
    }

    /**
     * Sets ranking_open_slots
     *
     * @param int|null $ranking_open_slots ranking_open_slots
     *
     * @return self
     */
    public function setRankingOpenSlots($ranking_open_slots)
    {
        if (is_null($ranking_open_slots)) {
            array_push($this->openAPINullablesSetToNull, 'ranking_open_slots');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ranking_open_slots', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ranking_open_slots'] = $ranking_open_slots;

        return $this;
    }

    /**
     * Gets ranking_open_slots_remaining
     *
     * @return int|null
     */
    public function getRankingOpenSlotsRemaining()
    {
        return $this->container['ranking_open_slots_remaining'];
    }

    /**
     * Sets ranking_open_slots_remaining
     *
     * @param int|null $ranking_open_slots_remaining ranking_open_slots_remaining
     *
     * @return self
     */
    public function setRankingOpenSlotsRemaining($ranking_open_slots_remaining)
    {
        if (is_null($ranking_open_slots_remaining)) {
            array_push($this->openAPINullablesSetToNull, 'ranking_open_slots_remaining');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ranking_open_slots_remaining', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ranking_open_slots_remaining'] = $ranking_open_slots_remaining;

        return $this;
    }

    /**
     * Gets open_for_ranking
     *
     * @return bool|null
     */
    public function getOpenForRanking()
    {
        return $this->container['open_for_ranking'];
    }

    /**
     * Sets open_for_ranking
     *
     * @param bool|null $open_for_ranking open_for_ranking
     *
     * @return self
     */
    public function setOpenForRanking($open_for_ranking)
    {
        if (is_null($open_for_ranking)) {
            array_push($this->openAPINullablesSetToNull, 'open_for_ranking');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('open_for_ranking', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['open_for_ranking'] = $open_for_ranking;

        return $this;
    }

    /**
     * Gets ranged_cut_off
     *
     * @return bool|null
     */
    public function getRangedCutOff()
    {
        return $this->container['ranged_cut_off'];
    }

    /**
     * Sets ranged_cut_off
     *
     * @param bool|null $ranged_cut_off ranged_cut_off
     *
     * @return self
     */
    public function setRangedCutOff($ranged_cut_off)
    {
        if (is_null($ranged_cut_off)) {
            array_push($this->openAPINullablesSetToNull, 'ranged_cut_off');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ranged_cut_off', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ranged_cut_off'] = $ranged_cut_off;

        return $this;
    }

    /**
     * Gets allowed_specialization
     *
     * @return string|null
     */
    public function getAllowedSpecialization()
    {
        return $this->container['allowed_specialization'];
    }

    /**
     * Sets allowed_specialization
     *
     * @param string|null $allowed_specialization allowed_specialization
     *
     * @return self
     */
    public function setAllowedSpecialization($allowed_specialization)
    {
        if (is_null($allowed_specialization)) {
            array_push($this->openAPINullablesSetToNull, 'allowed_specialization');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allowed_specialization', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allowed_specialization'] = $allowed_specialization;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


