<?php
/**
 * SarAdmissionReqsTaggingsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * USM Academic Systems Integration Api
 *
 * Integration API for multiple legacy systems and web apps
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rbsgaridan@usm.edu.ph
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * SarAdmissionReqsTaggingsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SarAdmissionReqsTaggingsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2SarSarAdmissionReqsTaggingsPost' => [
            'application/json-patch+json; x-api-version=2.0',
            'application/json; x-api-version=2.0',
            'text/json; x-api-version=2.0',
            'application/*+json; x-api-version=2.0',
        ],
        'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut' => [
            'application/json-patch+json; x-api-version=2.0',
            'application/json; x-api-version=2.0',
            'text/json; x-api-version=2.0',
            'application/*+json; x-api-version=2.0',
        ],
        'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut' => [
            'application/json-patch+json; x-api-version=2.0',
            'application/json; x-api-version=2.0',
            'text/json; x-api-version=2.0',
            'application/*+json; x-api-version=2.0',
        ],
        'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put' => [
            'application/json-patch+json; x-api-version=2.0',
            'application/json; x-api-version=2.0',
            'text/json; x-api-version=2.0',
            'application/*+json; x-api-version=2.0',
        ],
        'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut' => [
            'application/json-patch+json; x-api-version=2.0',
            'application/json; x-api-version=2.0',
            'text/json; x-api-version=2.0',
            'application/*+json; x-api-version=2.0',
        ],
        'getAdmissionRequirement' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsPost
     *
     * Create a new Admission Requirement checklist for a student
     *
     * @param  \OpenAPI\Client\Model\AdmissionRequirementDto $admission_requirement_dto  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SarSarAdmissionReqsTaggingsPost($admission_requirement_dto = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'][0])
    {
        $this->apiV2SarSarAdmissionReqsTaggingsPostWithHttpInfo($admission_requirement_dto, $contentType);
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsPostWithHttpInfo
     *
     * Create a new Admission Requirement checklist for a student
     *
     * @param  \OpenAPI\Client\Model\AdmissionRequirementDto $admission_requirement_dto  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SarSarAdmissionReqsTaggingsPostWithHttpInfo($admission_requirement_dto = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'][0])
    {
        $request = $this->apiV2SarSarAdmissionReqsTaggingsPostRequest($admission_requirement_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsPostAsync
     *
     * Create a new Admission Requirement checklist for a student
     *
     * @param  \OpenAPI\Client\Model\AdmissionRequirementDto $admission_requirement_dto  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsPostAsync($admission_requirement_dto = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'][0])
    {
        return $this->apiV2SarSarAdmissionReqsTaggingsPostAsyncWithHttpInfo($admission_requirement_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsPostAsyncWithHttpInfo
     *
     * Create a new Admission Requirement checklist for a student
     *
     * @param  \OpenAPI\Client\Model\AdmissionRequirementDto $admission_requirement_dto  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsPostAsyncWithHttpInfo($admission_requirement_dto = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'][0])
    {
        $returnType = '';
        $request = $this->apiV2SarSarAdmissionReqsTaggingsPostRequest($admission_requirement_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SarSarAdmissionReqsTaggingsPost'
     *
     * @param  \OpenAPI\Client\Model\AdmissionRequirementDto $admission_requirement_dto  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SarSarAdmissionReqsTaggingsPostRequest($admission_requirement_dto = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsPost'][0])
    {



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($admission_requirement_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($admission_requirement_dto));
            } else {
                $httpBody = $admission_requirement_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut
     *
     * Update a student&#39;s HS certificate of graduation submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagCertOfGradInput $tag_cert_of_grad_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut($student_no, $campus_id, $tag_cert_of_grad_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'][0])
    {
        $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutWithHttpInfo($student_no, $campus_id, $tag_cert_of_grad_input, $contentType);
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutWithHttpInfo
     *
     * Update a student&#39;s HS certificate of graduation submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagCertOfGradInput $tag_cert_of_grad_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutWithHttpInfo($student_no, $campus_id, $tag_cert_of_grad_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'][0])
    {
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutRequest($student_no, $campus_id, $tag_cert_of_grad_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutAsync
     *
     * Update a student&#39;s HS certificate of graduation submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagCertOfGradInput $tag_cert_of_grad_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutAsync($student_no, $campus_id, $tag_cert_of_grad_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'][0])
    {
        return $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutAsyncWithHttpInfo($student_no, $campus_id, $tag_cert_of_grad_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutAsyncWithHttpInfo
     *
     * Update a student&#39;s HS certificate of graduation submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagCertOfGradInput $tag_cert_of_grad_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutAsyncWithHttpInfo($student_no, $campus_id, $tag_cert_of_grad_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'][0])
    {
        $returnType = '';
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutRequest($student_no, $campus_id, $tag_cert_of_grad_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagCertOfGradInput $tag_cert_of_grad_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPutRequest($student_no, $campus_id, $tag_cert_of_grad_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'][0])
    {

        // verify the required parameter 'student_no' is set
        if ($student_no === null || (is_array($student_no) && count($student_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_no when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdCertOfGradPut'
            );
        }



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings/{studentNo}/{campusId}/cert-of-grad';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($student_no !== null) {
            $resourcePath = str_replace(
                '{' . 'studentNo' . '}',
                ObjectSerializer::toPathValue($student_no),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tag_cert_of_grad_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tag_cert_of_grad_input));
            } else {
                $httpBody = $tag_cert_of_grad_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut
     *
     * Update a student&#39;s Form 137a submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagFrom137aInput $tag_from137a_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut($student_no, $campus_id, $tag_from137a_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'][0])
    {
        $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutWithHttpInfo($student_no, $campus_id, $tag_from137a_input, $contentType);
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutWithHttpInfo
     *
     * Update a student&#39;s Form 137a submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagFrom137aInput $tag_from137a_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutWithHttpInfo($student_no, $campus_id, $tag_from137a_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'][0])
    {
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutRequest($student_no, $campus_id, $tag_from137a_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutAsync
     *
     * Update a student&#39;s Form 137a submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagFrom137aInput $tag_from137a_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutAsync($student_no, $campus_id, $tag_from137a_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'][0])
    {
        return $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutAsyncWithHttpInfo($student_no, $campus_id, $tag_from137a_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutAsyncWithHttpInfo
     *
     * Update a student&#39;s Form 137a submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagFrom137aInput $tag_from137a_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutAsyncWithHttpInfo($student_no, $campus_id, $tag_from137a_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'][0])
    {
        $returnType = '';
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutRequest($student_no, $campus_id, $tag_from137a_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagFrom137aInput $tag_from137a_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPutRequest($student_no, $campus_id, $tag_from137a_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'][0])
    {

        // verify the required parameter 'student_no' is set
        if ($student_no === null || (is_array($student_no) && count($student_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_no when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdForm137aPut'
            );
        }



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings/{studentNo}/{campusId}/form137a';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($student_no !== null) {
            $resourcePath = str_replace(
                '{' . 'studentNo' . '}',
                ObjectSerializer::toPathValue($student_no),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tag_from137a_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tag_from137a_input));
            } else {
                $httpBody = $tag_from137a_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put
     *
     * Update a student&#39;s Form 138 submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagForm138Input $tag_form138_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put($student_no, $campus_id, $tag_form138_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'][0])
    {
        $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutWithHttpInfo($student_no, $campus_id, $tag_form138_input, $contentType);
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutWithHttpInfo
     *
     * Update a student&#39;s Form 138 submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagForm138Input $tag_form138_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutWithHttpInfo($student_no, $campus_id, $tag_form138_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'][0])
    {
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutRequest($student_no, $campus_id, $tag_form138_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutAsync
     *
     * Update a student&#39;s Form 138 submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagForm138Input $tag_form138_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutAsync($student_no, $campus_id, $tag_form138_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'][0])
    {
        return $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutAsyncWithHttpInfo($student_no, $campus_id, $tag_form138_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutAsyncWithHttpInfo
     *
     * Update a student&#39;s Form 138 submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagForm138Input $tag_form138_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutAsyncWithHttpInfo($student_no, $campus_id, $tag_form138_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'][0])
    {
        $returnType = '';
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutRequest($student_no, $campus_id, $tag_form138_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagForm138Input $tag_form138_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138PutRequest($student_no, $campus_id, $tag_form138_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'][0])
    {

        // verify the required parameter 'student_no' is set
        if ($student_no === null || (is_array($student_no) && count($student_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_no when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagForm138Put'
            );
        }



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings/{studentNo}/{campusId}/tag-form138';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($student_no !== null) {
            $resourcePath = str_replace(
                '{' . 'studentNo' . '}',
                ObjectSerializer::toPathValue($student_no),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tag_form138_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tag_form138_input));
            } else {
                $httpBody = $tag_form138_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut
     *
     * Update a student&#39;s PSA Birth Certificate submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagPsaInput $tag_psa_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut($student_no, $campus_id, $tag_psa_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'][0])
    {
        $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutWithHttpInfo($student_no, $campus_id, $tag_psa_input, $contentType);
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutWithHttpInfo
     *
     * Update a student&#39;s PSA Birth Certificate submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagPsaInput $tag_psa_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutWithHttpInfo($student_no, $campus_id, $tag_psa_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'][0])
    {
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutRequest($student_no, $campus_id, $tag_psa_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutAsync
     *
     * Update a student&#39;s PSA Birth Certificate submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagPsaInput $tag_psa_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutAsync($student_no, $campus_id, $tag_psa_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'][0])
    {
        return $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutAsyncWithHttpInfo($student_no, $campus_id, $tag_psa_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutAsyncWithHttpInfo
     *
     * Update a student&#39;s PSA Birth Certificate submission status
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagPsaInput $tag_psa_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutAsyncWithHttpInfo($student_no, $campus_id, $tag_psa_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'][0])
    {
        $returnType = '';
        $request = $this->apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutRequest($student_no, $campus_id, $tag_psa_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'
     *
     * @param  string $student_no  (required)
     * @param  int $campus_id  (required)
     * @param  \OpenAPI\Client\Model\TagPsaInput $tag_psa_input  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPutRequest($student_no, $campus_id, $tag_psa_input = null, string $contentType = self::contentTypes['apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'][0])
    {

        // verify the required parameter 'student_no' is set
        if ($student_no === null || (is_array($student_no) && count($student_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_no when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SarSarAdmissionReqsTaggingsStudentNoCampusIdTagPsaPut'
            );
        }



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings/{studentNo}/{campusId}/tag-psa';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($student_no !== null) {
            $resourcePath = str_replace(
                '{' . 'studentNo' . '}',
                ObjectSerializer::toPathValue($student_no),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($tag_psa_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($tag_psa_input));
            } else {
                $httpBody = $tag_psa_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAdmissionRequirement
     *
     * @param  string $student_no student_no (required)
     * @param  int $campus_id campus_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAdmissionRequirement'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AdmissionRequirementDto
     */
    public function getAdmissionRequirement($student_no, $campus_id, $tenant_id = null, string $contentType = self::contentTypes['getAdmissionRequirement'][0])
    {
        list($response) = $this->getAdmissionRequirementWithHttpInfo($student_no, $campus_id, $tenant_id, $contentType);
        return $response;
    }

    /**
     * Operation getAdmissionRequirementWithHttpInfo
     *
     * @param  string $student_no (required)
     * @param  int $campus_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAdmissionRequirement'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AdmissionRequirementDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAdmissionRequirementWithHttpInfo($student_no, $campus_id, $tenant_id = null, string $contentType = self::contentTypes['getAdmissionRequirement'][0])
    {
        $request = $this->getAdmissionRequirementRequest($student_no, $campus_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\AdmissionRequirementDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AdmissionRequirementDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AdmissionRequirementDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\AdmissionRequirementDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AdmissionRequirementDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAdmissionRequirementAsync
     *
     * @param  string $student_no (required)
     * @param  int $campus_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAdmissionRequirement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAdmissionRequirementAsync($student_no, $campus_id, $tenant_id = null, string $contentType = self::contentTypes['getAdmissionRequirement'][0])
    {
        return $this->getAdmissionRequirementAsyncWithHttpInfo($student_no, $campus_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAdmissionRequirementAsyncWithHttpInfo
     *
     * @param  string $student_no (required)
     * @param  int $campus_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAdmissionRequirement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAdmissionRequirementAsyncWithHttpInfo($student_no, $campus_id, $tenant_id = null, string $contentType = self::contentTypes['getAdmissionRequirement'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AdmissionRequirementDto';
        $request = $this->getAdmissionRequirementRequest($student_no, $campus_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAdmissionRequirement'
     *
     * @param  string $student_no (required)
     * @param  int $campus_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAdmissionRequirement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAdmissionRequirementRequest($student_no, $campus_id, $tenant_id = null, string $contentType = self::contentTypes['getAdmissionRequirement'][0])
    {

        // verify the required parameter 'student_no' is set
        if ($student_no === null || (is_array($student_no) && count($student_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_no when calling getAdmissionRequirement'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling getAdmissionRequirement'
            );
        }



        $resourcePath = '/api/v2/sar/SarAdmissionReqsTaggings/{studentNo}/campus/{campusId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($student_no !== null) {
            $resourcePath = str_replace(
                '{' . 'studentNo' . '}',
                ObjectSerializer::toPathValue($student_no),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain; x-api-version=2.0', 'application/json; x-api-version=2.0', 'text/json; x-api-version=2.0', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
