<?php
/**
 * SubjectScheduleApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * USM Academic Systems Integration Api
 *
 * Integration API for multiple legacy systems and web apps
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rbsgaridan@usm.edu.ph
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * SubjectScheduleApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubjectScheduleApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet' => [
            'application/json',
        ],
        'apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet' => [
            'application/json',
        ],
        'apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet' => [
            'application/json',
        ],
        'apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet
     *
     * @param  int $sched_id sched_id (required)
     * @param  int $campus_id campus_id (required)
     * @param  string $term_id term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet($sched_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'][0])
    {
        $this->apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetWithHttpInfo($sched_id, $campus_id, $term_id, $contentType);
    }

    /**
     * Operation apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetWithHttpInfo
     *
     * @param  int $sched_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetWithHttpInfo($sched_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'][0])
    {
        $request = $this->apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetRequest($sched_id, $campus_id, $term_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetAsync
     *
     * @param  int $sched_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetAsync($sched_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'][0])
    {
        return $this->apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetAsyncWithHttpInfo($sched_id, $campus_id, $term_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetAsyncWithHttpInfo
     *
     * @param  int $sched_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetAsyncWithHttpInfo($sched_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetRequest($sched_id, $campus_id, $term_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'
     *
     * @param  int $sched_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGetRequest($sched_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'][0])
    {

        // verify the required parameter 'sched_id' is set
        if ($sched_id === null || (is_array($sched_id) && count($sched_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sched_id when calling apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2SubjectScheduleCampusCampusIdSchedSchedIdTermTermIdGet'
            );
        }


        $resourcePath = '/api/v2/SubjectSchedule/campus/{campusId}/sched/{schedId}/term/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sched_id !== null) {
            $resourcePath = str_replace(
                '{' . 'schedId' . '}',
                ObjectSerializer::toPathValue($sched_id),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet
     *
     * @param  string $student_id student_id (required)
     * @param  int $campus_id campus_id (required)
     * @param  int $term_id term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet($student_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'][0])
    {
        $this->apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetWithHttpInfo($student_id, $campus_id, $term_id, $contentType);
    }

    /**
     * Operation apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetWithHttpInfo
     *
     * @param  string $student_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetWithHttpInfo($student_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'][0])
    {
        $request = $this->apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetRequest($student_id, $campus_id, $term_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetAsync
     *
     * @param  string $student_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetAsync($student_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'][0])
    {
        return $this->apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($student_id, $campus_id, $term_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo
     *
     * @param  string $student_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($student_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetRequest($student_id, $campus_id, $term_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'
     *
     * @param  string $student_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGetRequest($student_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'][0])
    {

        // verify the required parameter 'student_id' is set
        if ($student_id === null || (is_array($student_id) && count($student_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_id when calling apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2SubjectScheduleCurriculumStudentStudentIdCampusCampusIdTermTermIdGet'
            );
        }


        $resourcePath = '/api/v2/SubjectSchedule/curriculum/student/{studentId}/campus/{campusId}/term/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($student_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studentId' . '}',
                ObjectSerializer::toPathValue($student_id),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet
     *
     * @param  int $section_id section_id (required)
     * @param  int $campus_id campus_id (required)
     * @param  int $term_id term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet($section_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'][0])
    {
        $this->apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetWithHttpInfo($section_id, $campus_id, $term_id, $contentType);
    }

    /**
     * Operation apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetWithHttpInfo
     *
     * @param  int $section_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetWithHttpInfo($section_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'][0])
    {
        $request = $this->apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetRequest($section_id, $campus_id, $term_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetAsync
     *
     * @param  int $section_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetAsync($section_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'][0])
    {
        return $this->apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($section_id, $campus_id, $term_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo
     *
     * @param  int $section_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($section_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetRequest($section_id, $campus_id, $term_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'
     *
     * @param  int $section_id (required)
     * @param  int $campus_id (required)
     * @param  int $term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGetRequest($section_id, $campus_id, $term_id, string $contentType = self::contentTypes['apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'][0])
    {

        // verify the required parameter 'section_id' is set
        if ($section_id === null || (is_array($section_id) && count($section_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $section_id when calling apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2SubjectScheduleSectionsSectionIdCampusCampusIdTermTermIdGet'
            );
        }


        $resourcePath = '/api/v2/SubjectSchedule/sections/{sectionId}/campus/{campusId}/term/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($section_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sectionId' . '}',
                ObjectSerializer::toPathValue($section_id),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet
     *
     * @param  int $subject_id subject_id (required)
     * @param  int $campus_id campus_id (required)
     * @param  string $term_id term_id (required)
     * @param  int $current_term_id current_term_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet($subject_id, $campus_id, $term_id, $current_term_id = null, string $contentType = self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'][0])
    {
        $this->apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetWithHttpInfo($subject_id, $campus_id, $term_id, $current_term_id, $contentType);
    }

    /**
     * Operation apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetWithHttpInfo
     *
     * @param  int $subject_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  int $current_term_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetWithHttpInfo($subject_id, $campus_id, $term_id, $current_term_id = null, string $contentType = self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'][0])
    {
        $request = $this->apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetRequest($subject_id, $campus_id, $term_id, $current_term_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetAsync
     *
     * @param  int $subject_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  int $current_term_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetAsync($subject_id, $campus_id, $term_id, $current_term_id = null, string $contentType = self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'][0])
    {
        return $this->apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($subject_id, $campus_id, $term_id, $current_term_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo
     *
     * @param  int $subject_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  int $current_term_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetAsyncWithHttpInfo($subject_id, $campus_id, $term_id, $current_term_id = null, string $contentType = self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetRequest($subject_id, $campus_id, $term_id, $current_term_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'
     *
     * @param  int $subject_id (required)
     * @param  int $campus_id (required)
     * @param  string $term_id (required)
     * @param  int $current_term_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGetRequest($subject_id, $campus_id, $term_id, $current_term_id = null, string $contentType = self::contentTypes['apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'][0])
    {

        // verify the required parameter 'subject_id' is set
        if ($subject_id === null || (is_array($subject_id) && count($subject_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subject_id when calling apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2SubjectScheduleSubjectIdCampusCampusIdTermTermIdGet'
            );
        }



        $resourcePath = '/api/v2/SubjectSchedule/{subjectId}/campus/{campusId}/term/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $current_term_id,
            'currentTermId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($subject_id !== null) {
            $resourcePath = str_replace(
                '{' . 'subjectId' . '}',
                ObjectSerializer::toPathValue($subject_id),
                $resourcePath
            );
        }
        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
