<?php
/**
 * TrialProgramApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * USM Academic Systems Integration Api
 *
 * Integration API for multiple legacy systems and web apps
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rbsgaridan@usm.edu.ph
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * TrialProgramApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrialProgramApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2TrialProgramCurriculumStudentStudentIdGet' => [
            'application/json',
        ],
        'apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet' => [
            'application/json',
        ],
        'apiV2TrialProgramEvaluationStudentStudentIdGet' => [
            'application/json',
        ],
        'apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet' => [
            'application/json',
        ],
        'apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet' => [
            'application/json',
        ],
        'apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdGet
     *
     * Curriculum view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdGet($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'][0])
    {
        $this->apiV2TrialProgramCurriculumStudentStudentIdGetWithHttpInfo($student_id, $tenant_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdGetWithHttpInfo
     *
     * Curriculum view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdGetWithHttpInfo($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'][0])
    {
        $request = $this->apiV2TrialProgramCurriculumStudentStudentIdGetRequest($student_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdGetAsync
     *
     * Curriculum view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdGetAsync($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'][0])
    {
        return $this->apiV2TrialProgramCurriculumStudentStudentIdGetAsyncWithHttpInfo($student_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdGetAsyncWithHttpInfo
     *
     * Curriculum view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdGetAsyncWithHttpInfo($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramCurriculumStudentStudentIdGetRequest($student_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramCurriculumStudentStudentIdGet'
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdGetRequest($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdGet'][0])
    {

        // verify the required parameter 'student_id' is set
        if ($student_id === null || (is_array($student_id) && count($student_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_id when calling apiV2TrialProgramCurriculumStudentStudentIdGet'
            );
        }



        $resourcePath = '/api/v2/TrialProgram/curriculum/student/{studentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($student_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studentId' . '}',
                ObjectSerializer::toPathValue($student_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet
     *
     * Curriculum view for student
     *
     * @param  string $student_id  (required)
     * @param  int $term_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet($student_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'][0])
    {
        $this->apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetWithHttpInfo($student_id, $term_id, $tenant_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetWithHttpInfo
     *
     * Curriculum view for student
     *
     * @param  string $student_id  (required)
     * @param  int $term_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetWithHttpInfo($student_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'][0])
    {
        $request = $this->apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetRequest($student_id, $term_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetAsync
     *
     * Curriculum view for student
     *
     * @param  string $student_id  (required)
     * @param  int $term_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetAsync($student_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'][0])
    {
        return $this->apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetAsyncWithHttpInfo($student_id, $term_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetAsyncWithHttpInfo
     *
     * Curriculum view for student
     *
     * @param  string $student_id  (required)
     * @param  int $term_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetAsyncWithHttpInfo($student_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetRequest($student_id, $term_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'
     *
     * @param  string $student_id  (required)
     * @param  int $term_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGetRequest($student_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'][0])
    {

        // verify the required parameter 'student_id' is set
        if ($student_id === null || (is_array($student_id) && count($student_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_id when calling apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2TrialProgramCurriculumStudentStudentIdTermTermIdGet'
            );
        }



        $resourcePath = '/api/v2/TrialProgram/curriculum/student/{studentId}/term/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($student_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studentId' . '}',
                ObjectSerializer::toPathValue($student_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2TrialProgramEvaluationStudentStudentIdGet
     *
     * Evaluation view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramEvaluationStudentStudentIdGet($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'][0])
    {
        $this->apiV2TrialProgramEvaluationStudentStudentIdGetWithHttpInfo($student_id, $tenant_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramEvaluationStudentStudentIdGetWithHttpInfo
     *
     * Evaluation view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramEvaluationStudentStudentIdGetWithHttpInfo($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'][0])
    {
        $request = $this->apiV2TrialProgramEvaluationStudentStudentIdGetRequest($student_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramEvaluationStudentStudentIdGetAsync
     *
     * Evaluation view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramEvaluationStudentStudentIdGetAsync($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'][0])
    {
        return $this->apiV2TrialProgramEvaluationStudentStudentIdGetAsyncWithHttpInfo($student_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramEvaluationStudentStudentIdGetAsyncWithHttpInfo
     *
     * Evaluation view for adviser
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramEvaluationStudentStudentIdGetAsyncWithHttpInfo($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramEvaluationStudentStudentIdGetRequest($student_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramEvaluationStudentStudentIdGet'
     *
     * @param  string $student_id  (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramEvaluationStudentStudentIdGetRequest($student_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramEvaluationStudentStudentIdGet'][0])
    {

        // verify the required parameter 'student_id' is set
        if ($student_id === null || (is_array($student_id) && count($student_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_id when calling apiV2TrialProgramEvaluationStudentStudentIdGet'
            );
        }



        $resourcePath = '/api/v2/TrialProgram/evaluation/student/{studentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($student_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studentId' . '}',
                ObjectSerializer::toPathValue($student_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet
     *
     * @param  int $section_id section_id (required)
     * @param  int $term_id term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet($section_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'][0])
    {
        $this->apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetWithHttpInfo($section_id, $term_id, $tenant_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetWithHttpInfo
     *
     * @param  int $section_id (required)
     * @param  int $term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetWithHttpInfo($section_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'][0])
    {
        $request = $this->apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetRequest($section_id, $term_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetAsync
     *
     * @param  int $section_id (required)
     * @param  int $term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetAsync($section_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'][0])
    {
        return $this->apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetAsyncWithHttpInfo($section_id, $term_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetAsyncWithHttpInfo
     *
     * @param  int $section_id (required)
     * @param  int $term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetAsyncWithHttpInfo($section_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetRequest($section_id, $term_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'
     *
     * @param  int $section_id (required)
     * @param  int $term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGetRequest($section_id, $term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'][0])
    {

        // verify the required parameter 'section_id' is set
        if ($section_id === null || (is_array($section_id) && count($section_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $section_id when calling apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'
            );
        }

        // verify the required parameter 'term_id' is set
        if ($term_id === null || (is_array($term_id) && count($term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $term_id when calling apiV2TrialProgramGetstudentsbysectionSectionIdTermIdGet'
            );
        }



        $resourcePath = '/api/v2/TrialProgram/getstudentsbysection/{sectionId}/{termId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($section_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sectionId' . '}',
                ObjectSerializer::toPathValue($section_id),
                $resourcePath
            );
        }
        // path params
        if ($term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'termId' . '}',
                ObjectSerializer::toPathValue($term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet
     *
     * @param  int $campus_id campus_id (required)
     * @param  int $previous_term_id previous_term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet($campus_id, $previous_term_id, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'][0])
    {
        $this->apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetWithHttpInfo($campus_id, $previous_term_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetWithHttpInfo
     *
     * @param  int $campus_id (required)
     * @param  int $previous_term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetWithHttpInfo($campus_id, $previous_term_id, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'][0])
    {
        $request = $this->apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetRequest($campus_id, $previous_term_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetAsync
     *
     * @param  int $campus_id (required)
     * @param  int $previous_term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetAsync($campus_id, $previous_term_id, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'][0])
    {
        return $this->apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetAsyncWithHttpInfo($campus_id, $previous_term_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetAsyncWithHttpInfo
     *
     * @param  int $campus_id (required)
     * @param  int $previous_term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetAsyncWithHttpInfo($campus_id, $previous_term_id, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetRequest($campus_id, $previous_term_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'
     *
     * @param  int $campus_id (required)
     * @param  int $previous_term_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGetRequest($campus_id, $previous_term_id, string $contentType = self::contentTypes['apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'][0])
    {

        // verify the required parameter 'campus_id' is set
        if ($campus_id === null || (is_array($campus_id) && count($campus_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $campus_id when calling apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'
            );
        }

        // verify the required parameter 'previous_term_id' is set
        if ($previous_term_id === null || (is_array($previous_term_id) && count($previous_term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $previous_term_id when calling apiV2TrialProgramGetstudentstreebycampusCampusIdPreviousTermIdGet'
            );
        }


        $resourcePath = '/api/v2/TrialProgram/getstudentstreebycampus/{campusId}/{previousTermId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($campus_id !== null) {
            $resourcePath = str_replace(
                '{' . 'campusId' . '}',
                ObjectSerializer::toPathValue($campus_id),
                $resourcePath
            );
        }
        // path params
        if ($previous_term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'previousTermId' . '}',
                ObjectSerializer::toPathValue($previous_term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet
     *
     * @param  string $student_id student_id (required)
     * @param  int $current_term_id current_term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet($student_id, $current_term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'][0])
    {
        $this->apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetWithHttpInfo($student_id, $current_term_id, $tenant_id, $contentType);
    }

    /**
     * Operation apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetWithHttpInfo
     *
     * @param  string $student_id (required)
     * @param  int $current_term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetWithHttpInfo($student_id, $current_term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'][0])
    {
        $request = $this->apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetRequest($student_id, $current_term_id, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetAsync
     *
     * @param  string $student_id (required)
     * @param  int $current_term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetAsync($student_id, $current_term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'][0])
    {
        return $this->apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetAsyncWithHttpInfo($student_id, $current_term_id, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetAsyncWithHttpInfo
     *
     * @param  string $student_id (required)
     * @param  int $current_term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetAsyncWithHttpInfo($student_id, $current_term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetRequest($student_id, $current_term_id, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'
     *
     * @param  string $student_id (required)
     * @param  int $current_term_id (required)
     * @param  \OpenAPI\Client\Model\TenantDbs $tenant_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2TrialProgramStudentStudentIdTermCurrentTermIdGetRequest($student_id, $current_term_id, $tenant_id = null, string $contentType = self::contentTypes['apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'][0])
    {

        // verify the required parameter 'student_id' is set
        if ($student_id === null || (is_array($student_id) && count($student_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $student_id when calling apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'
            );
        }

        // verify the required parameter 'current_term_id' is set
        if ($current_term_id === null || (is_array($current_term_id) && count($current_term_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $current_term_id when calling apiV2TrialProgramStudentStudentIdTermCurrentTermIdGet'
            );
        }



        $resourcePath = '/api/v2/TrialProgram/student/{studentId}/term/{currentTermId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'TenantDbs', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($student_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studentId' . '}',
                ObjectSerializer::toPathValue($student_id),
                $resourcePath
            );
        }
        // path params
        if ($current_term_id !== null) {
            $resourcePath = str_replace(
                '{' . 'currentTermId' . '}',
                ObjectSerializer::toPathValue($current_term_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
